### 문제 정의
- 미국의 도시인 보스턴 1970년대 거주지에 대한 데이터를 바탕으로 주택 가격 예측해보기
- 답이 있는 데이터 -> 지도학습
- 연속적인 수치(가격) 예측 -> 회귀

In [1]:
# 경고창 무시 하는 코드
import warnings
warnings.filterwarnings(action='ignore')

In [3]:
# 라이브러리 불러오기
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# 보스턴 주택 데이터 불러오기
# 사이킷런 모델안에 공부용으로 데이터 만들어 놓은거 불러오기
from sklearn.datasets import fetch_openml
boston = fetch_openml(name = 'boston', as_frame = True)
boston

{'data':         CRIM    ZN  INDUS CHAS    NOX     RM   AGE     DIS RAD    TAX  \
 0    0.00632  18.0   2.31    0  0.538  6.575  65.2  4.0900   1  296.0
 1    0.02731   0.0   7.07    0  0.469  6.421  78.9  4.9671   2  242.0
 2    0.02729   0.0   7.07    0  0.469  7.185  61.1  4.9671   2  242.0
 3    0.03237   0.0   2.18    0  0.458  6.998  45.8  6.0622   3  222.0
 4    0.06905   0.0   2.18    0  0.458  7.147  54.2  6.0622   3  222.0
 ..       ...   ...    ...  ...    ...    ...   ...     ...  ..    ...
 501  0.06263   0.0  11.93    0  0.573  6.593  69.1  2.4786   1  273.0
 502  0.04527   0.0  11.93    0  0.573  6.120  76.7  2.2875   1  273.0
 503  0.06076   0.0  11.93    0  0.573  6.976  91.0  2.1675   1  273.0
 504  0.10959   0.0  11.93    0  0.573  6.794  89.3  2.3889   1  273.0
 505  0.04741   0.0  11.93    0  0.573  6.030  80.8  2.5050   1  273.0

      PTRATIO       B  LSTAT
 0       15.3  396.90   4.98
 1       17.8  396.90   9.14
 2       17.8  392.83   4.03
 3       18.7  394.63   2.94
 4       18.7  396.90   5.33
 ..       ...     ...    ...
 501     21.0  391.99   9.67
 502     21.0  396.90   9.08
 503     21.0  396.90   5.64
 504     21.0  393.45   6.48
 505     21.0  396.90   7.88

 [506 rows x 13 columns],
 'target': 0      24.0
 1      21.6
 2      34.7
 3      33.4
 4      36.2
        ...
 501    22.4
 502    20.6
 503    23.9
 504    22.0
 505    11.9
 Name: MEDV, Length: 506, dtype: float64,
 'frame':         CRIM    ZN  INDUS CHAS    NOX     RM   AGE     DIS RAD    TAX  \
 0    0.00632  18.0   2.31    0  0.538  6.575  65.2  4.0900   1  296.0
 1    0.02731   0.0   7.07    0  0.469  6.421  78.9  4.9671   2  242.0
 2    0.02729   0.0   7.07    0  0.469  7.185  61.1  4.9671   2  242.0
 3    0.03237   0.0   2.18    0  0.458  6.998  45.8  6.0622   3  222.0
 4    0.06905   0.0   2.18    0  0.458  7.147  54.2  6.0622   3  222.0
 ..       ...   ...    ...  ...    ...    ...   ...     ...  ..    ...
 501  0.06263   0.0  11.93    0  0.573  6.593  69.1  2.4786   1  273.0
 502  0.04527   0.0  11.93    0  0.573  6.120  76.7  2.2875   1  273.0
 503  0.06076   0.0  11.93    0  0.573  6.976  91.0  2.1675   1  273.0
 504  0.10959   0.0  11.93    0  0.573  6.794  89.3  2.3889   1  273.0
 505  0.04741   0.0  11.93    0  0.573  6.030  80.8  2.5050   1  273.0

      PTRATIO       B  LSTAT  MEDV
 0       15.3  396.90   4.98  24.0
 1       17.8  396.90   9.14  21.6
 2       17.8  392.83   4.03  34.7
 3       18.7  394.63   2.94  33.4
 4       18.7  396.90   5.33  36.2
 ..       ...     ...    ...   ...
 501     21.0  391.99   9.67  22.4
 502     21.0  396.90   9.08  20.6
 503     21.0  396.90   5.64  23.9
 504     21.0  393.45   6.48  22.0
 505     21.0  396.90   7.88  11.9

 [506 rows x 14 columns],
 'categories': None,
 'feature_names': ['CRIM',
  'ZN',
  'INDUS',
  'CHAS',
  'NOX',
  'RM',
  'AGE',
  'DIS',
  'RAD',
  'TAX',
  'PTRATIO',
  'B',
  'LSTAT'],
 'target_names': ['MEDV'],
 'DESCR': "**Author**:   \n**Source**: Unknown - Date unknown  \n**Please cite**:   \n\nThe Boston house-price data of Harrison, D. and Rubinfeld, D.L. 'Hedonic\nprices and the demand for clean air', J. Environ. Economics & Management,\nvol.5, 81-102, 1978.   Used in Belsley, Kuh & Welsch, 'Regression diagnostics\n...', Wiley, 1980.   N.B. Various transformations are used in the table on\npages 244-261 of the latter.\nVariables in order:\nCRIM     per capita crime rate by town\nZN       proportion of residential land zoned for lots over 25,000 sq.ft.\nINDUS    proportion of non-retail business acres per town\nCHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)\nNOX      nitric oxides concentration (parts per 10 million)\nRM       average number of rooms per dwelling\nAGE      proportion of owner-occupied units built prior to 1940\nDIS      weighted distances to five Boston employment centres\nRAD      index of accessibility to radial highways\nTAX      full-value property-tax rate per $10,000\nPTRATIO  pupil-teacher ratio by town\nB        1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town\nLSTAT    % lower status of the population\nMEDV     Median value of owner-occupied homes in $1000's\n\n\nInformation about the dataset\nCLASSTYPE: numeric\nCLASSINDEX: last\n\nDownloaded from openml.org.",
 'details': {'id': '531',
  'name': 'boston',
  'version': '1',
  'description_version': '1',
  'format': 'ARFF',
  'creator': ['D. and Rubinfeld', "D.L. 'Hedonic"],
  'collection_date': '1978',
  'upload_date': '2014-09-29T00:08:07',
  'language': 'English',
  'licence': 'Public',
  'url': 'https://openml.org/data/v1/download/52643/boston.arff',
  'parquet_url': 'https://data.openml.org/datasets/0000/0531/dataset_531.pq',
  'file_id': '52643',
  'default_target_attribute': 'MEDV',
  'tag': ['Data Science',
   'Housing Economics',
   'Kaggle',
   'OpenML-Reg19',
   'study_130',
   'Urban Studies'],
  'visibility': 'public',
  'status': 'active',
  'processing_date': '2020-11-20 20:16:37',
  'md5_checksum': 'cdd361fb886627eaa80c92f90d0610cc'},
 'url': 'https://www.openml.org/d/531'}

In [4]:
# 조회
boston.keys()

dict_keys(['data', 'target', 'frame', 'categories', 'feature_names', 'target_names', 'DESCR', 'details', 'url'])

In [5]:
print(boston.DESCR)

**Author**:
**Source**: Unknown - Date unknown
**Please cite**:

The Boston house-price data of Harrison, D. and Rubinfeld, D.L. 'Hedonic
prices and the demand for clean air', J. Environ. Economics & Management,
vol.5, 81-102, 1978.   Used in Belsley, Kuh & Welsch, 'Regression diagnostics
...', Wiley, 1980.   N.B. Various transformations are used in the table on
pages 244-261 of the latter.
Variables in order:
CRIM     per capita crime rate by town
ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
INDUS    proportion of non-retail business acres per town
CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
NOX      nitric oxides concentration (parts per 10 million)
RM       average number of rooms per dwelling
AGE      proportion of owner-occupied units built prior to 1940
DIS      weighted distances to five Boston employment centres
RAD      index of accessibility to radial highways
TAX      full-value property-tax rate per $10,000
PTRATIO  pupil-teacher ratio by town
B        1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town
LSTAT    % lower status of the population
MEDV     Median value of owner-occupied homes in $1000's


Information about the dataset
CLASSTYPE: numeric
CLASSINDEX: last

Downloaded from openml.org.

#### 설명변수 (원인: 예측값을 설명할 수 있는 변수)
CRIM: 범죄율  
INDUS: 비소매상업지역 면접 비율  
NOX: 일산화질소 농도  
RM : 주택당 방 수  
LSTAT: 인구 중 하위 계층 비율  
B: 인구 중 흑인 비율  
PTRATIO: 학생/교사 비율  
ZN: 25,000 평방피트를 초과 거주지역 비율  
CHAS : 찰스강의 경계에 위치한 경우는 1, 아니면 0  
AGE : 1940년 이전에 건축된 주택의 비율  
RAD : 고속도로 접근 인덱스  
DIS: 직업센터의 거리  
TAX: 재산세율  
    
#### 반응 변수(결과: 예측하고자 하는 값 )
MEDV: 주택가격 (1000달러 단위)

### 데이터 전처리
- X : 독립변수, 특성, 입력변수
- y : 종속변수, 타겟, 출력변수

In [6]:
boston.keys()

dict_keys(['data', 'target', 'frame', 'categories', 'feature_names', 'target_names', 'DESCR', 'details', 'url'])

In [7]:
# 데이터 프레임 형태로 전처리
X = pd.DataFrame(boston.data,
                 columns = boston.feature_names)
y = pd.Series(boston.target)

In [8]:
X.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33

In [9]:
y.head()
# 1000만 달러 단위

0    24.0
1    21.6
2    34.7
3    33.4
4    36.2
Name: MEDV, dtype: float64

In [10]:
X.info()

<class 'pandas.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 13 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    category
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    category
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
dtypes: category(2), float64(11)
memory usage: 44.7 KB

In [11]:
# X 특성 중에서 category 자료형을 수치형태(int)로 변환 하자
# astype() 사용
# CHAS, RAD
X[['CHAS', 'RAD']] = X[['CHAS', 'RAD']].astype('int64')

In [13]:
X.info()

<class 'pandas.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 13 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    int64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
dtypes: float64(11), int64(2)
memory usage: 51.5 KB

### train, test 분리
- train_test_split 함수 이용
- 순서 : X_train, X_test, y_train, y_test
- 7:3 비율, random_state = 0

In [14]:
from sklearn.model_selection import train_test_split

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size = 0.3,
                                                    random_state = 0)

In [18]:
# 트레인이 잘 섞여서 나왔는지 확인
X_train

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
141,1.62864,0.0,21.89,0,0.624,5.019,100.0,1.4394,4,437.0,21.2,396.90,34.41
272,0.11460,20.0,6.96,0,0.464,6.538,58.7,3.9175,3,223.0,18.6,394.96,7.73
135,0.55778,0.0,21.89,0,0.624,6.335,98.2,2.1107,4,437.0,21.2,394.67,16.96
298,0.06466,70.0,2.24,0,0.400,6.345,20.1,7.8278,5,358.0,14.8,368.24,4.97
122,0.09299,0.0,25.65,0,0.581,5.961,92.9,2.0869,2,188.0,19.1,378.09,17.93
...,...,...,...,...,...,...,...,...,...,...,...,...,...
323,0.28392,0.0,7.38,0,0.493,5.708,74.3,4.7211,5,287.0,19.6,391.13,11.74
192,0.08664,45.0,3.44,0,0.437,7.178,26.3,6.4798,5,398.0,15.2,390.49,2.87
117,0.15098,0.0,10.01,0,0.547,6.021,82.6,2.7474,6,432.0,17.8,394.51,10.30
47,0.22927,0.0,6.91,0,0.448,6.030,85.5,5.6894,3,233.0,17.9,392.74,18.80
172,0.13914,0.0,4.05,0,0.510,5.572,88.5,2.5961,5,296.0,16.6,396.90,14.69

In [19]:
y_train

141    14.4
272    24.4
135    18.1
298    22.5
122    20.5
       ...
323    18.5
192    36.4
117    19.2
47     16.6
172    23.1
Name: MEDV, Length: 354, dtype: float64

### LinearRegression 사용해서 모델 학습시키기

In [21]:
# 모델 선정단계

In [20]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score

In [22]:
# 모델 생성(초기화)
linear_model = LinearRegression()

In [23]:
# 학습 단계
linear_model.fit(X_train, y_train)

LinearRegression()

In [25]:
# 예측
y_pre = linear_model.predict(X_test)
y_pre

array([24.9357079 , 23.75163164, 29.32638296, 11.97534566, 21.37272478,
       19.19148525, 20.5717479 , 21.21154015, 19.04572003, 20.35463238,
        5.44119126, 16.93688709, 17.15482272,  5.3928209 , 40.20270696,
       32.31327348, 22.46213268, 36.50124666, 31.03737014, 23.17124551,
       24.74815321, 24.49939403, 20.6595791 , 30.4547583 , 22.32487164,
       10.18932894, 17.44286422, 18.26103077, 35.63299326, 20.81960303,
       18.27218007, 17.72047628, 19.33772473, 23.62254823, 28.97766856,
       19.45036239, 11.13170639, 24.81843595, 18.05294835, 15.59712226,
       26.21043403, 20.81140432, 22.17349382, 15.48367365, 22.62261604,
       24.88561528, 19.74754478, 23.0465628 ,  9.84579105, 24.36378793,
       21.47849008, 17.62118176, 24.39160873, 29.95102691, 13.57219422,
       21.53645439, 20.53306273, 15.03433182, 14.3232289 , 22.11929299,
       17.07321915, 21.54141094, 32.96766968, 31.371599  , 17.7860591 ,
       32.75069556, 18.74795323, 19.21428022, 19.41970047, 23.08087809,
       22.87732816, 24.06399098, 30.52824406, 28.71453508, 25.90763165,
        5.17596718, 36.8709072 , 23.76983849, 27.26064379, 19.25849042,
       28.41860517, 19.3008798 , 18.94922353, 38.00154059, 39.44096748,
       23.72297885, 24.83722534, 16.52015743, 25.9970546 , 16.73997072,
       15.48656983, 13.52825536, 24.12884363, 30.76919578, 22.18731163,
       19.8848644 ,  0.42275479, 24.86785849, 16.05692   , 17.42486412,
       25.49798527, 22.35171315, 32.66562689, 22.04428746, 27.29799885,
       23.20302026,  6.86196574, 14.869251  , 22.31804948, 29.18125768,
       33.22568234, 13.24392523, 19.67195771, 20.7502616 , 12.02271319,
       23.50067006,  5.55662571, 19.87634689,  9.27059783, 44.81787339,
       30.56017983, 12.44394048, 17.33192202, 21.48313292, 23.52664913,
       20.49877266, 35.09161099, 13.22639935, 20.70321163, 35.35582833,
       19.45050576, 13.81603561, 14.15654562, 23.03678503, 15.07521258,
       30.9662041 , 25.23236632, 15.43763716, 24.06406534,  9.93080346,
       15.01618901, 21.06098873, 32.87115732, 27.80927747, 25.91293794,
       15.27877362, 30.97489404, 27.81107682, 14.5068157 ,  7.57369946,
       28.3348068 , 25.04341153])

In [26]:
# 교차검증
result = cross_val_score(linear_model,
                X_train, y_train,
                cv = 5) # 5개로 나누어 교차 검증
result

array([0.7246982 , 0.58082515, 0.77515092, 0.72161474, 0.78935797])

In [27]:
result.mean()

np.float64(0.718329397431592)

### 선형 회귀 평가 지표
- MSE : 평균제곱오차
- RMSE : 평균제곱오차에 루트를 씌운
- MAE : 오차에 절댓값을 씌워 평균낸 것
- r2 : 편차에 비한 오차

In [28]:
from sklearn.metrics import mean_squared_error # 평균제곱오차
from sklearn.metrics import mean_absolute_error # 평균절대오차
from sklearn.metrics import r2_score # 결정 계수

In [29]:
# y_test <-> y_pre
# MSE 평균 제곱 오차
# mean_squared_error(실제값, 예측값)
mean_squared_error(y_test, y_pre)

27.195965766883475

In [30]:
# RMSE 평균 제곱 오차에 루트
# sklearn 모듈에 따로 RMSE도구가 없는 이유 : 루트 -> sqrt(), MSE속성 안에 squared = True/False
np.sqrt(mean_squared_error(y_test, y_pre))

np.float64(5.214975145375429)

In [31]:
# MAE 평균 절대 오차
mean_absolute_error(y_test, y_pre)
# MSE, RMSE, MAE 값만 봤을 때는 오차가 작은건지, 큰건지 파악이 불가능하다

3.609904060381831

In [33]:
# R2 score
# 결정계수
r2_score(y_test, y_pre)
# 1에 가까울수록 좋음.

0.6733825506400164

In [34]:
# 모델 자체 스코어 함수
linear_model.score(X_test, y_test)

0.6733825506400164

In [35]:
linear_model.score(X_train, y_train)

0.7645451026942549

- 현재 선형 모델은 성능이 좋지 못함.
- 모델의 성능을 개선해야할 필요가 있음!
- 선형 모델은 데이터가 많을수록 성능이 빛을 발하는 모델이다!
- 데이터를 늘려보자!

### 특성 확장
- 특성 확장을 해서 모델의 성능을 높여보자!
- 13개의 수치 데이터가 따로도 의미가 있지만, 같이 있었을 때에도 집값에 영향이 있는지 확인해보자!
- 컬럼 두개를 묶어서 하나의 특성으로 만들자는 의미.(두개의 값을 곱해서)

In [36]:
extended_X_train = X_train.copy() # 원본 데이터 안건드릴려고 복사함.

In [37]:
# 반복문을 사용하여 특성 확장
for col1 in X_train.columns : 
    for col2 in X_train.columns :
        extended_X_train[col1+'x'+col2] = X_train[col1] * X_train[col2]

In [38]:
extended_X_train

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,...,LSTATxCHAS,LSTATxNOX,LSTATxRM,LSTATxAGE,LSTATxDIS,LSTATxRAD,LSTATxTAX,LSTATxPTRATIO,LSTATxB,LSTATxLSTAT
141,1.62864,0.0,21.89,0,0.624,5.019,100.0,1.4394,4,437.0,...,0.0,21.47184,172.70379,3441.000,49.529754,137.64,15037.17,729.492,13657.3290,1184.0481
272,0.11460,20.0,6.96,0,0.464,6.538,58.7,3.9175,3,223.0,...,0.0,3.58672,50.53874,453.751,30.282275,23.19,1723.79,143.778,3053.0408,59.7529
135,0.55778,0.0,21.89,0,0.624,6.335,98.2,2.1107,4,437.0,...,0.0,10.58304,107.44160,1665.472,35.797472,67.84,7411.52,359.552,6693.6032,287.6416
298,0.06466,70.0,2.24,0,0.400,6.345,20.1,7.8278,5,358.0,...,0.0,1.98800,31.53465,99.897,38.904166,24.85,1779.26,73.556,1830.1528,24.7009
122,0.09299,0.0,25.65,0,0.581,5.961,92.9,2.0869,2,188.0,...,0.0,10.41733,106.88073,1665.697,37.418117,35.86,3370.84,342.463,6779.1537,321.4849
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
323,0.28392,0.0,7.38,0,0.493,5.708,74.3,4.7211,5,287.0,...,0.0,5.78782,67.01192,872.282,55.425714,58.70,3369.38,230.104,4591.8662,137.8276
192,0.08664,45.0,3.44,0,0.437,7.178,26.3,6.4798,5,398.0,...,0.0,1.25419,20.60086,75.481,18.597026,14.35,1142.26,43.624,1120.7063,8.2369
117,0.15098,0.0,10.01,0,0.547,6.021,82.6,2.7474,6,432.0,...,0.0,5.63410,62.01630,850.780,28.298220,61.80,4449.60,183.340,4063.4530,106.0900
47,0.22927,0.0,6.91,0,0.448,6.030,85.5,5.6894,3,233.0,...,0.0,8.42240,113.36400,1607.400,106.960720,56.40,4380.40,336.520,7383.5120,353.4400
172,0.13914,0.0,4.05,0,0.510,5.572,88.5,2.5961,5,296.0,...,0.0,7.49190,81.85268,1300.065,38.136709,73.45,4348.24,243.854,5830.4610,215.7961

In [39]:
# X_test 특성 확장
extended_X_test = X_test.copy()

In [40]:
for col1 in X_test.columns : 
    for col2 in X_test.columns :
        extended_X_test[col1+'x'+col2] = X_test[col1] * X_test[col2]

In [42]:
extended_X_test

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,...,LSTATxCHAS,LSTATxNOX,LSTATxRM,LSTATxAGE,LSTATxDIS,LSTATxRAD,LSTATxTAX,LSTATxPTRATIO,LSTATxB,LSTATxLSTAT
329,0.06724,0.0,3.24,0,0.460,6.333,17.2,5.2146,4,430.0,...,0.0,3.37640,46.48422,126.248,38.275164,29.36,3156.20,124.046,2754.0414,53.8756
371,9.23230,0.0,18.10,0,0.631,6.216,100.0,1.1691,24,666.0,...,0.0,6.01343,59.23848,953.000,11.141523,228.72,6346.98,192.506,3489.4095,90.8209
219,0.11425,0.0,13.89,1,0.550,6.373,92.4,3.3633,5,276.0,...,10.5,5.77500,66.91650,970.200,35.314650,52.50,2898.00,172.200,4134.2700,110.2500
403,24.80170,0.0,18.10,0,0.693,5.349,96.0,1.7028,24,666.0,...,0.0,13.70061,105.74973,1897.920,33.664356,474.48,13166.82,399.354,7846.7130,390.8529
78,0.05646,0.0,12.83,0,0.437,6.232,53.7,5.0141,5,398.0,...,0.0,5.39258,76.90288,662.658,61.873994,61.70,4911.32,230.758,4768.1760,152.2756
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,...,0.0,2.44114,38.09351,288.886,32.311526,15.99,1183.26,99.671,2115.4770,28.4089
428,7.36711,0.0,18.10,0,0.679,6.193,78.1,1.9356,24,666.0,...,0.0,14.61208,133.27336,1680.712,41.654112,516.48,14332.32,434.704,2081.6296,463.1104
385,16.81180,0.0,18.10,0,0.700,5.277,98.1,1.4261,24,666.0,...,0.0,21.56700,162.58437,3022.461,43.938141,739.44,20519.46,622.362,12228.4890,949.2561
308,0.49298,0.0,9.90,0,0.544,6.635,82.5,3.3175,4,304.0,...,0.0,2.46976,30.12290,374.550,15.061450,18.16,1380.16,83.536,1801.9260,20.6116
5,0.02985,0.0,2.18,0,0.458,6.430,58.7,6.0622,3,222.0,...,0.0,2.38618,33.50030,305.827,31.584062,15.63,1156.62,97.427,2053.3652,27.1441

In [43]:
extended_X_test.info()

<class 'pandas.DataFrame'>
Index: 152 entries, 329 to 5
Columns: 182 entries, CRIM to LSTATxLSTAT
dtypes: float64(176), int64(6)
memory usage: 217.3 KB

In [44]:
extended_X_test.columns

Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       ...
       'LSTATxCHAS', 'LSTATxNOX', 'LSTATxRM', 'LSTATxAGE', 'LSTATxDIS',
       'LSTATxRAD', 'LSTATxTAX', 'LSTATxPTRATIO', 'LSTATxB', 'LSTATxLSTAT'],
      dtype='str', length=182)

In [45]:
# 확장된 데이터로 다시 모델을 학습시켜 보자!!
linear_model2 = LinearRegression()
linear_model2.fit(extended_X_train, y_train)

LinearRegression()

In [46]:
linear_model2.score(extended_X_test, y_test)

0.6681396381286437

In [ ]:
# 특성이 너어어어무 많아져서 과대적합이 와버렸구나...........
# 정규화가 정답이다!!

#### 정규화
Lasso: L1 규제를 사용하여 중요도가 낮은 특성의 가중치를 아예 0으로 만들어 불필요한 특성을 제거하고, 모델을 단순하게 만들어 줍니다.

Ridge: L2 규제를 사용하여 모든 특성의 가중치 크기를 전반적으로 작게 줄여주고, 특정 특성이 과도한 영향을 미치지 못하도록 억제하여 과대적합을 막아줍니다.

In [47]:
# L1 규제 : Lasso
from sklearn.linear_model import Lasso

In [52]:
# 모델 생성(초기화)
lasso_model = Lasso(alpha = 10) # alpha : 얼마나 규제를 가할건지 -> 1.0 기본값

# 규제가 강해지면 과대적합을 줄일 수 있다. 하지만 오차가 커질 가능성이 있다.

In [53]:
# 학습
lasso_model.fit(extended_X_train, y_train)

Lasso(alpha=10)

In [54]:
lasso_model.score(extended_X_test, y_test)

0.7467008426432002

In [55]:
# L2 규제 : Ridge
from sklearn.linear_model import Ridge

In [56]:
# 모델 생성(초기화)
ridge_model = Ridge(alpha = 100)

In [57]:
# 학습
ridge_model.fit(extended_X_train, y_train)

Ridge(alpha=100)

In [58]:
ridge_model.score(extended_X_test, y_test)

0.7767755128062253

In [ ]:
# 규제를 적용한 결과 점수가 더 올랐다!
# Lasso 처럼 변수가 소거 되는 것보다, ridge 처럼 모든 변수의 가중치를 부드럽게 줄여나가는 방식이
# 모델의 안정성과 성능 면에서 더 적합했기 때문에
# 오늘은 릿지 규제를 쓰는게 적당했다! 좋았다

In [ ]:
# Lasso를 쓰는 경우?
# 1. 중요하지 않은 특성(노이즈)을 제거하고 싶을 때
# 2. 강한 독립변수들(특성들)만 남기고 싶을 때